spring:
  profiles:
    active: default
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tcc_product
    username: andy
    password: password
server:
  port: 7081
tcc:
  jdbc:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/TCC?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: andy
    password: password

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/tcc_product
    username: uca
    password: password

tcc:
  jdbc:
    url: jdbc:mysql://192.168.63.195:3306/TCC?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: uca
    password: password