spring:
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tcc_order
    username: andy
    password: password
server:
  port: 7080

tcc:
  jdbc:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/TCC?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: andy
    password: password
    c3p0:
      initial-pool-size: 10
      min-pool-size: 10
      max-pool-size: 30
      acquire-increment: 3
      max-idle-time: 1800
      checkout-timeout: 30000